#/bin/bash
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew upgrade
brew tap ==> Auto-updated Homebrew!
brew tap Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
brew tap ==> New Formulae
brew tap apache-arrow
brew tap apache-arrow-glib
brew tap bumpversion
brew tap cassandra-reaper
brew tap cmusfm
brew tap cstore_fdw
brew tap diskus
brew tap fff
brew tap git-absorb
brew tap gtranslator
brew tap h3
brew tap jinja2-cli
brew tap jp
brew tap libkeccak
brew tap libopenmpt
brew tap mage
brew tap man-db
brew tap phpmd
brew tap protoc-gen-go
brew tap reprepro
brew tap sha3sum
brew tap signal-cli
brew tap spirv-cross
brew tap step
brew tap swagger2markup-cli
brew tap tesseract-lang
brew tap ungit
brew tap usbredir
brew tap vulkan-headers
brew tap ==> Updated Formulae
brew tap abcde
brew tap abcmidi
brew tap activemq-cpp
brew tap aescrypt-packetizer
brew tap afflib
brew tap afio
brew tap agedu
brew tap algernon
brew tap allure
brew tap amqp-cpp
brew tap angular-cli
brew tap annie
brew tap ansible
brew tap ansible-lint
brew tap apache-opennlp
brew tap app-engine-java
brew tap arangodb
brew tap aravis
brew tap arm-linux-gnueabihf-binutils
brew tap armadillo
brew tap arpack
brew tap artifactory
brew tap asciidoctorj
brew tap asio
brew tap ask-cli
brew tap ats2-postiats
brew tap auditbeat
brew tap autoconf-archive
brew tap autogen
brew tap avfs
brew tap awscli
brew tap azure-cli
brew tap azure-storage-cpp
brew tap babeld
brew tap babl
brew tap bacula-fd
brew tap ballerina
brew tap bartycrouch
brew tap bat
brew tap bazel
brew tap bettercap
brew tap bind
brew tap binutils
brew tap bison
brew tap bit
brew tap bitrise
brew tap bluetoothconnector
brew tap caddy
brew tap cassandra
brew tap cassandra@2.1
brew tap cassandra@2.2
brew tap certbot
brew tap cglm
brew tap checkbashisms
brew tap chronograf
brew tap clojure
brew tap clutter-gst
brew tap cmus
brew tap cockroach
brew tap cocoapods
brew tap composer
brew tap conan
brew tap confluent-oss
brew tap conjure-up
brew tap container-diff
brew tap convox
brew tap coq
brew tap cppcheck
brew tap cromwell
brew tap crowdin
brew tap cryfs
brew tap crystal
brew tap curl
brew tap curl-openssl
brew tap cython
brew tap davmail
brew tap dbhash
brew tap dcmtk
brew tap devd
brew tap dhall
brew tap diff-pdf
brew tap direnv
brew tap dmd
brew tap dnsviz
brew tap docker
brew tap doitlive
brew tap dosbox-x
brew tap efl
brew tap eiffelstudio
brew tap elasticsearch
brew tap elixir
brew tap embulk
brew tap eslint
brew tap etcd
brew tap exploitdb
brew tap fd
brew tap ffmpeg
brew tap file-formula
brew tap firebase-cli
brew tap fish
brew tap flake8
brew tap fn
brew tap fonttools
brew tap frugal
brew tap futhark
brew tap fwup
brew tap fx
brew tap geocode-glib
brew tap gerbil-scheme
brew tap ghc
brew tap git-extras
brew tap git-lfs
brew tap git-quick-stats
brew tap git-secrets
brew tap gitlab-runner
brew tap gmsh
brew tap gnatsd
brew tap gnome-recipes
brew tap gnupg
brew tap go@1.10
brew tap gomplate
brew tap google-java-format
brew tap goreleaser
brew tap gradle
brew tap gradle-completion
brew tap groonga
brew tap groovy
brew tap gspell
brew tap gtk+3
brew tap gx
brew tap gx-go
brew tap hadolint
brew tap handbrake
brew tap haproxy
brew tap harfbuzz
brew tap hcloud
brew tap helmfile
brew tap highlight
brew tap hivemind
brew tap hledger
brew tap htop
brew tap httpd
brew tap hub
brew tap ice
brew tap igv
brew tap imagemagick
brew tap imagemagick@6
brew tap inetutils
brew tap influxdb
brew tap ipv6calc
brew tap ipython
brew tap iso-codes
brew tap istioctl
brew tap jdupes
brew tap jenkins
brew tap jenkins-lts
brew tap jfrog-cli-go
brew tap juju
brew tap kibana
brew tap kotlin
brew tap kube-aws
brew tap kubeless
brew tap kubeprod
brew tap kubernetes-cli
brew tap kustomize
brew tap lammps
brew tap ledger
brew tap leiningen
brew tap libassuan
brew tap libextractor
brew tap libgphoto2
brew tap libgweather
brew tap libhttpserver
brew tap libidn2
brew tap libmagic
brew tap libosinfo
brew tap libphonenumber
brew tap libpqxx
brew tap libpsl
brew tap libpulsar
brew tap libraw
brew tap librealsense
brew tap librsvg
brew tap libssh
brew tap libtermkey
brew tap libtiff
brew tap libu2f-host
brew tap libuv
brew tap libvirt
brew tap libvmaf
brew tap libvpx
brew tap libxslt
brew tap lighttpd
brew tap linkerd
brew tap links
brew tap liquibase
brew tap logrotate
brew tap logstash
brew tap lolcat
brew tap lxc
brew tap lynis
brew tap macvim
brew tap mariadb
brew tap mariadb@10.0
brew tap mariadb@10.1
brew tap mariadb@10.2
brew tap math-comp
brew tap maxima
brew tap maxwell
brew tap mesa
brew tap meson
brew tap metricbeat
brew tap minio
brew tap minio-mc
brew tap miniserve
brew tap mkcert
brew tap mkl-dnn
brew tap mono
brew tap mosquitto
brew tap mpd
brew tap mpv
brew tap mrboom
brew tap mutt
brew tap mysql
brew tap mysql@5.7
brew tap nativefier
brew tap nats-streaming-server
brew tap ncdu
brew tap netpbm
brew tap newsboat
brew tap nexus
brew tap nghttp2
brew tap ngircd
brew tap nim
brew tap ninja
brew tap nkf
brew tap nnn
brew tap node
brew tap node@10
brew tap ocrmypdf
brew tap odpi
brew tap offlineimap
brew tap opa
brew tap openal-soft
brew tap openconnect
brew tap opendetex
brew tap openimageio
brew tap osquery
brew tap osrm-backend
brew tap overmind
brew tap paket
brew tap pandoc-citeproc
brew tap pdftoedn
brew tap pdftoipe
brew tap petsc
brew tap petsc-complex
brew tap pgroonga
brew tap pgweb
brew tap phoronix-test-suite
brew tap php
brew tap php@7.1
brew tap php@7.2
brew tap phpunit
brew tap picat
brew tap pipenv
brew tap pixman
brew tap plantuml
brew tap pmd
brew tap pony-stable
brew tap poppler
brew tap postgresql
brew tap postgresql@9.4
brew tap postgresql@9.5
brew tap postgresql@9.6
brew tap presto
brew tap prettier
brew tap primesieve
brew tap profanity
brew tap prometheus
brew tap psql2csv
brew tap pulumi
brew tap pushpin
brew tap pypy
brew tap pypy3
brew tap pyside
brew tap python
brew tap python@2
brew tap qpdf
brew tap qt
brew tap rabbitmq
brew tap rawtoaces
brew tap rclone
brew tap rebar3
brew tap repo
brew tap rgbds
brew tap rke
brew tap rocksdb
brew tap rom-tools
brew tap rtags
brew tap rtv
brew tap ruby@2.4
brew tap safe
brew tap sccache
brew tap scipy
brew tap scrcpy
brew tap shared-mime-info
brew tap shellz
brew tap ship
brew tap simutrans
brew tap sip
brew tap siril
brew tap skaffold
brew tap solr
brew tap sound-touch
brew tap spatialindex
brew tap sphinx
brew tap sphinx-doc
brew tap sqldiff
brew tap sqlite
brew tap sqlite-analyzer
brew tap squid
brew tap streamlink
brew tap swift-protobuf
brew tap swiftformat
brew tap syncthing
brew tap telegraf
brew tap terraform_landscape
brew tap tesseract
brew tap texinfo
brew tap tgui
brew tap thors-serializer
brew tap timidity
brew tap tmux-xpanes
brew tap tomcat
brew tap topgrade
brew tap tor
brew tap traefik
brew tap typescript
brew tap umlet
brew tap unbound
brew tap unrar
brew tap upx
brew tap urbit
brew tap urdfdom
brew tap v8
brew tap valabind
brew tap vim
brew tap vim@7.4
brew tap vips
brew tap wabt
brew tap weaver
brew tap weechat
brew tap wget
brew tap whois
brew tap wtf
brew tap xsimd
brew tap xtensor
brew tap yamllint
brew tap yara
brew tap ydcv
brew tap youtube-dl
brew tap zsh
brew tap ==> Renamed Formulae
brew tap resin-cli -> balena-cli
brew tap todolist -> ultralist
brew tap 
brew tap cbde/stuff
brew tap cowbell/stuff
brew tap homebrew/cask
brew tap homebrew/cask-versions
brew tap homebrew/core
brew tap homebrew/dupes
brew tap homebrew/php
brew tap homebrew/services
brew tap homebrew/versions
brew tap neovim/neovim
brew install adns
brew install adr-tools
brew install apr
brew install apr-util
brew install aspell
brew install autoconf
brew install autojump
brew install automake
brew install aws-shell
brew install awscli
brew install bfg
brew install cask
brew install chromedriver
brew install cmake
brew install coreutils
brew install direnv
brew install emacs
brew install freetds
brew install freetype
brew install gdbm
brew install gettext
brew install gitversion
brew install glib
brew install gmp
brew install gnupg
brew install gnutls
brew install go
brew install haskell-stack
brew install hub
brew install icu4c
brew install ipcalc
brew install jenv
brew install jpeg
brew install jq
brew install libassuan
brew install libffi
brew install libgcrypt
brew install libgpg-error
brew install libksba
brew install libpng
brew install libpq
brew install libtasn1
brew install libtermkey
brew install libtool
brew install libunistring
brew install libusb
brew install libuv
brew install libvterm
brew install libxml2
brew install libyaml
brew install libzip
brew install mcrypt
brew install mhash
brew install mongodb
brew install mono
brew install msgpack
brew install mysql
brew install mysql@5.6
brew install nettle
brew install node
brew install npth
brew install nvm
brew install oniguruma
brew install openssl
brew install p11-kit
brew install pcre
brew install perl
brew install phantomjs
brew install php71
brew install php@7.1
brew install pinentry
brew install pkg-config
brew install pyenv
brew install python
brew install python@2
brew install rea-as
brew install rea-slip-utils
brew install readline
brew install ruby
brew install sbt
brew install scala
brew install shush
brew install sqlite
brew install the_silver_searcher
brew install tig
brew install tree
brew install unibilium
brew install unixodbc
brew install vim
brew install watchman
brew install webp
brew install wp-cli
brew install xz
brew install yarn
brew install zsh-completions
brew install zsh-syntax-highlighting
brew cask install alfred
brew cask install docker
brew cask install dotnet-sdk
brew cask install dropbox
brew cask install evernote
brew cask install firefox
brew cask install google-chrome
brew cask install graphiql
brew cask install hyper
brew cask install iterm2
brew cask install java8
brew cask install keepassx
brew cask install mysqlworkbench
brew cask install openoffice
brew cask install skype
brew cask install slack
brew cask install spectacle
brew cask install spotify
brew cask install virtualbox
brew cask install visual-studio-code
brew cask install zoomus
brew cleanup
brew cask cleanup
