#/bin/bash
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew upgrade
brew tap ==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
brew tap https://github.com/Homebrew/brew#donations
brew tap ==> Auto-updated Homebrew!
brew tap Updated 3 taps (homebrew/cask-versions, homebrew/core, homebrew/cask).
brew tap ==> New Formulae
brew tap aws-okta
brew tap cash-cli
brew tap docker-credential-helper-ecr
brew tap docker-machine-driver-hyperkit
brew tap eslint
brew tap fauna-shell
brew tap gambit
brew tap geogram
brew tap go@1.10
brew tap json11
brew tap kustomize
brew tap libsignal-protocol-c
brew tap luarocks
brew tap luit
brew tap miniserve
brew tap pcapplusplus
brew tap perltidy
brew tap petsc-complex
brew tap pulumi
brew tap range-v3
brew tap topgrade
brew tap wiremock-standalone
brew tap wskdeploy
brew tap xsimd
brew tap zlog
brew tap ==> Updated Formulae
brew tap acpica
brew tap activemq
brew tap alexjs
brew tap angular-cli
brew tap annie
brew tap ansible
brew tap ansible-cmdb
brew tap arangodb
brew tap ark
brew tap arm-linux-gnueabihf-binutils
brew tap armadillo
brew tap artifactory
brew tap ats2-postiats
brew tap augeas
brew tap automake
brew tap aws-elasticbeanstalk
brew tap aws-sdk-cpp
brew tap awscli
brew tap azure-cli
brew tap b2-tools
brew tap babel
brew tap babl
brew tap ballerina
brew tap bat
brew tap bdw-gc
brew tap beast
brew tap bench
brew tap bettercap
brew tap bind
brew tap bison
brew tap bitrise
brew tap bwfmetaedit
brew tap byobu
brew tap caffe
brew tap cake
brew tap ceres-solver
brew tap chakra
brew tap checkstyle
brew tap cimg
brew tap circleci
brew tap ckan
brew tap closure-compiler
brew tap cmake
brew tap cmark-gfm
brew tap cockroach
brew tap commandbox
brew tap composer
brew tap confuse
brew tap convox
brew tap cquery
brew tap crystal
brew tap dartsim
brew tap dateutils
brew tap ddclient
brew tap deark
brew tap di
brew tap diff-pdf
brew tap discount
brew tap dita-ot
brew tap dmd
brew tap docfx
brew tap docker
brew tap doctl
brew tap draco
brew tap dropbear
brew tap druid
brew tap duck
brew tap dwarfutils
brew tap dxpy
brew tap dynare
brew tap efl
brew tap elasticsearch@5.6
brew tap elektra
brew tap elixir
brew tap elm
brew tap erlang
brew tap erlang@19
brew tap erlang@20
brew tap ethereum
brew tap exercism
brew tap exomizer
brew tap expat
brew tap exploitdb
brew tap fbi-servefiles
brew tap fd
brew tap fdclone
brew tap feedgnuplot
brew tap fibjs
brew tap field3d
brew tap firebase-cli
brew tap flann
brew tap flow
brew tap fluent-bit
brew tap fn
brew tap folly
brew tap fortio
brew tap fselect
brew tap futhark
brew tap fwup
brew tap gdbm
brew tap gegl
brew tap geoipupdate
brew tap get_iplayer
brew tap ghostscript
brew tap giflib
brew tap gimme
brew tap git-annex
brew tap git-archive-all
brew tap git-cola
brew tap git-extras
brew tap git-quick-stats
brew tap gitlab-runner
brew tap gjstest
brew tap glib
brew tap glib-networking
brew tap glslviewer
brew tap gmt
brew tap gmt@4
brew tap gnumeric
brew tap go
brew tap go-statik
brew tap gocryptfs
brew tap godep
brew tap goenv
brew tap goffice
brew tap goreleaser
brew tap gpac
brew tap grails
brew tap graphite2
brew tap gromacs
brew tap groovy
brew tap groovysdk
brew tap grpc
brew tap grunt-completion
brew tap gst-plugins-bad
brew tap gtk-vnc
brew tap hadolint
brew tap hadoop
brew tap harfbuzz
brew tap hcloud
brew tap hdf5
brew tap helmfile
brew tap heroku
brew tap hexgui
brew tap hh
brew tap hub
brew tap hugo
brew tap i2p
brew tap igv
brew tap imagemagick
brew tap imagemagick@6
brew tap imageoptim-cli
brew tap influxdb
brew tap ios-webkit-debug-proxy
brew tap iso-codes
brew tap jenkins
brew tap jenkins-job-builder
brew tap jenkins-lts
brew tap jfrog-cli-go
brew tap jhipster
brew tap juju
brew tap kafka
brew tap kallisto
brew tap kibana@5.6
brew tap knot
brew tap knot-resolver
brew tap kontena
brew tap kops
brew tap kore
brew tap kotlin
brew tap kubectx
brew tap kubeless
brew tap kubernetes-helm
brew tap kubernetes-service-catalog-client
brew tap ldc
brew tap libatomic_ops
brew tap libbi
brew tap libgsf
brew tap libhdhomerun
brew tap libical
brew tap libmatio
brew tap libomp
brew tap libpcap
brew tap libphonenumber
brew tap libpq
brew tap libpqxx
brew tap libqalculate
brew tap librealsense
brew tap libsoup
brew tap libssh
brew tap libtensorflow
brew tap libuv
brew tap lighttpd
brew tap linkerd
brew tap log4cplus
brew tap lrzsz
brew tap lua
brew tap lua@5.1
brew tap lxc
brew tap lynis
brew tap macvim
brew tap mariadb
brew tap mariadb@10.1
brew tap mariadb@10.2
brew tap mdcat
brew tap mdds
brew tap memcached
brew tap meson
brew tap metabase
brew tap micro
brew tap micronaut
brew tap minizinc
brew tap mint
brew tap mkcert
brew tap mkdocs
brew tap mkl-dnn
brew tap mkvtoolnix
brew tap mlkit
brew tap modules
brew tap mongodb@3.6
brew tap mongoose
brew tap mono
brew tap mosquitto
brew tap mpd
brew tap msgpack
brew tap mujs
brew tap nagios
brew tap naturaldocs
brew tap nco
brew tap ncview
brew tap neo4j
brew tap netcdf
brew tap nghttp2
brew tap nginx
brew tap nnn
brew tap node
brew tap node-build
brew tap node@6
brew tap node@8
brew tap nsd
brew tap ntl
brew tap ntp
brew tap numpy
brew tap nyancat
brew tap ocaml
brew tap ocrmypdf
brew tap octave
brew tap open-mpi
brew tap openapi-generator
brew tap opencoarrays
brew tap openssh
brew tap openssl
brew tap openssl@1.1
brew tap openvdb
brew tap osc
brew tap osmium-tool
brew tap osquery
brew tap p11-kit
brew tap pango
brew tap parallel
brew tap pc6001vx
brew tap pcb2gcode
brew tap pcl
brew tap pdal
brew tap pdftoedn
brew tap pdftoipe
brew tap percona-server@5.6
brew tap perl-build
brew tap pgbouncer
brew tap php
brew tap php@7.1
brew tap phpmyadmin
brew tap phpunit
brew tap pilosa
brew tap pkcs11-helper
brew tap plantuml
brew tap poppler
brew tap postgresql
brew tap postgresql@9.4
brew tap postgresql@9.5
brew tap postgresql@9.6
brew tap prest
brew tap prettier
brew tap primesieve
brew tap protobuf-c
brew tap pushpin
brew tap pyenv
brew tap pyside
brew tap qemu
brew tap qpdf
brew tap qtkeychain
brew tap quicktype
brew tap radare2
brew tap rancher-cli
brew tap re2c
brew tap rename
brew tap riemann-client
brew tap rocksdb
brew tap roswell
brew tap rsyslog
brew tap rtv
brew tap ruby-build
brew tap s6
brew tap safe
brew tap saxon
brew tap sceptre
brew tap schismtracker
brew tap scrcpy
brew tap shibboleth-sp
brew tap singular
brew tap skaffold
brew tap skafos
brew tap skktools
brew tap sleuthkit
brew tap smlnj
brew tap sonarqube
brew tap spdlog
brew tap sphinx-doc
brew tap sqoop
brew tap sratoolkit
brew tap ssh-copy-id
brew tap ssh-permit-a38
brew tap sshguard
brew tap sshtrix
brew tap stern
brew tap stone-soup
brew tap svtplay-dl
brew tap swift
brew tap swift-protobuf
brew tap swiftformat
brew tap sysdig
brew tap tarsnap-gui
brew tap telegraf
brew tap teleport
brew tap termius
brew tap terraform
brew tap terraform_landscape
brew tap terragrunt
brew tap thors-serializer
brew tap titlecase
brew tap tmate
brew tap tomcat
brew tap tomcat-native
brew tap tomcat@7
brew tap tomcat@8
brew tap tox
brew tap translate-shell
brew tap travis
brew tap tty-solitaire
brew tap twoping
brew tap ubertooth
brew tap unixodbc
brew tap uriparser
brew tap util-linux
brew tap v8
brew tap vala
brew tap vegeta
brew tap verilator
brew tap vim
brew tap virtuoso
brew tap vrpn
brew tap vsts-cli
brew tap vtk
brew tap watchexec
brew tap webdis
brew tap webpack
brew tap wine
brew tap winetricks
brew tap wireguard-tools
brew tap wp-cli
brew tap wtf
brew tap xcodegen
brew tap xml-tooling-c
brew tap xtensor
brew tap yafc
brew tap yara
brew tap you-get
brew tap youtube-dl
brew tap yubico-piv-tool
brew tap zanata-client
brew tap zero-install
brew tap zsh-completions
brew tap ==> Deleted Formulae
brew tap dirmngr
brew tap ghc@8.0
brew tap gnupg@2.0
brew tap gpg-agent
brew tap node@4
brew tap 
brew tap cbde/stuff
brew tap cowbell/stuff
brew tap homebrew/cask
brew tap homebrew/cask-versions
brew tap homebrew/core
brew tap homebrew/dupes
brew tap homebrew/php
brew tap homebrew/services
brew tap homebrew/versions
brew tap neovim/neovim
brew install adns
brew install adr-tools
brew install apr
brew install apr-util
brew install aspell
brew install autoconf
brew install autojump
brew install automake
brew install aws-shell
brew install awscli
brew install bfg
brew install cask
brew install chromedriver
brew install cmake
brew install coreutils
brew install direnv
brew install emacs
brew install freetds
brew install freetype
brew install gdbm
brew install gettext
brew install gitversion
brew install glib
brew install gmp
brew install gnupg
brew install gnutls
brew install go
brew install hub
brew install icu4c
brew install ipcalc
brew install jenv
brew install jpeg
brew install jq
brew install libassuan
brew install libffi
brew install libgcrypt
brew install libgpg-error
brew install libksba
brew install libpng
brew install libpq
brew install libtasn1
brew install libtermkey
brew install libtool
brew install libunistring
brew install libusb
brew install libuv
brew install libvterm
brew install libxml2
brew install libyaml
brew install libzip
brew install mcrypt
brew install mhash
brew install mono
brew install msgpack
brew install mysql
brew install mysql@5.6
brew install nettle
brew install node
brew install npth
brew install nvm
brew install oniguruma
brew install openssl
brew install p11-kit
brew install pcre
brew install perl
brew install phantomjs
brew install php71
brew install php@7.1
brew install pinentry
brew install pkg-config
brew install pyenv
brew install python
brew install rea-as
brew install rea-slip-utils
brew install readline
brew install ruby
brew install sbt
brew install scala
brew install shush
brew install sqlite
brew install the_silver_searcher
brew install unibilium
brew install unixodbc
brew install vim
brew install watchman
brew install webp
brew install wp-cli
brew install xz
brew install yarn
brew install zsh-completions
brew install zsh-syntax-highlighting
brew cask install alfred
brew cask install docker
brew cask install dotnet-sdk
brew cask install dropbox
brew cask install evernote
brew cask install firefox
brew cask install google-chrome
brew cask install graphiql
brew cask install hyper
brew cask install iterm2
brew cask install java8
brew cask install keepassx
brew cask install mysqlworkbench
brew cask install openoffice
brew cask install skype
brew cask install slack
brew cask install spectacle
brew cask install spotify
brew cask install virtualbox
brew cask install visual-studio-code
brew cleanup
brew cask cleanup
